version: "3"

services:
    web:
        hostname: web
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: jarvis-api
        command: uvicorn main:app --host 0.0.0.0 --port 80
        volumes:
          - ./app:/app
        ports:
            - "80:80"
        env_file:
            - .env
        restart: always
